apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yaml
  - name: grafana-k8s-dashboard
    files:
      - dashboard_definitions/k8s-cluster-dashboard.json
  - name: grafana-gpu-dashboard
    files:
      - dashboard_definitions/nvidia-gpu-dashboard.json
  - name: grafana-prometheus-datasource
    files:
      - prometheus-datasource.yaml

generatorOptions:
  disableNameSuffixHash: false
