apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-ingress
  namespace: monitoring
  labels:
    app: matrix
spec:
  ingressClassName: cilium
  rules:
  - host: matrix.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: matrix
            port:
              number: 8008
