apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - secret-init.yaml
  - rbac.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - bootstrap-job.yaml
