- include_tasks: disable_swap.yaml

- include_tasks: prepare_apt.yaml

- include_tasks: install_kubeadm_kubelet.yaml

- include_tasks: install_crio.yaml

- include_tasks: os_network_config.yaml

- include_tasks: configure_ceph_kernel.yaml
  when: ENABLE_CEPH | bool

- include_tasks: configure_cuda.yaml
  when: labels.compute is defined and labels.compute == 'cuda'